JNG-4308 deep copy test
BlackBeltTechnology/judo-runtime-core-jsl pull request #106
Opened 2022-12-06 16:05 UTC by gaborflorian

2022-12-06 16:15 UTC, robertcsakany requested changes

2022-12-06 16:15 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CompositionRelationshipsTest.java
> +        assertNotEquals(entityA.getSingleRequiredConA().get__identifier(),singleRequiredConA.get__identifier());
Space after , !

2022-12-06 16:15 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CompositionRelationshipsTest.java
> +        //When we add a composition Entity we must copy it, because that comp entity belong the created entity
Put the model init here from @Berfore

2022-12-07 10:56 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CompositionRelationshipsTest.java
> +        //When we add a composition Entity we must copy it, because that comp entity belong the created entity
[c26c058](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/106/commits/c26c058eef801889ef8c1ad20c24162841342beb)

2022-12-07 10:56 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/CompositionRelationshipsTest.java
> +        assertNotEquals(entityA.getSingleRequiredConA().get__identifier(),singleRequiredConA.get__identifier());
[c26c058](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/106/commits/c26c058eef801889ef8c1ad20c24162841342beb)

2022-12-07 11:28 UTC, blackbelt-oss approved these changes

2022-12-07 11:30 UTC, robertcsakany approved these changes

2022-12-07 12:15 UTC, noherczeg approved these changes

2022-12-07 12:16 UTC, bencegelei approved these changes

2022-12-07 12:50 UTC, merged