JNG-4297 Creating Judo test methodology
BlackBeltTechnology/judo-runtime-core-jsl pull request #122
Opened 2023-01-05 02:45 UTC by fmagnucz

<table>
<td>
  <a href="https://blackbelt.atlassian.net/browse/JNG-4297" title="JNG-4297" target="_blank"><img alt="Story" src="https://blackbelt.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />JNG-4297</a>  Creating Judo test methodology
  </td></table>
  <br />

2023-01-05 11:42 UTC, robertcsakany requested changes

2023-01-05 11:42 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/pom.xml
> +                <version>3.10.1</version>
Remove version - already defined in parent

2023-01-05 11:42 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/pom.xml
> +                    <target>11</target>
Remove source and target - already defined in parent

2023-01-05 11:42 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/pom.xml
> +        </dependency>
Do not use direct version reference in dependency for our nodule.

1. Please create a property in parent pom.xml in block 1.0.0.20230105_022024_241fcd45_feature_JNG_4297_Creating_Judo_test_methodolog
2. Put this dependency to parent's pom section with version using the property defined earlier ${judo-requirement-report-version}
3. In this place use the dependency without version and scope.
4. When a new property is defined in a parent's pom referencing our module, in judo-ng's (and judo-community too in this case) project-meta.yaml have to add the module as dependency. In our case in the judo-runtime-core JSL entry will have a new dependency which is judo-requirement-report.

2023-01-05 11:42 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
> -
Why the licence block have beem removed? Please add back!

2023-01-05 12:50 UTC, gaborflorian approved these changes

2023-01-05 13:42 UTC, bencegelei approved these changes

2023-01-09 19:08 UTC, fmagnucz commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/FunctionsTest.java
> -
The merge process was the wrong.

2023-01-10 08:04 UTC, gaborflorian approved these changes

2023-01-10 13:37 UTC, bencegelei approved these changes

2023-01-10 13:50 UTC, noherczeg approved these changes

2023-01-10 19:24 UTC, robertcsakany approved these changes

2023-01-10 22:47 UTC, merged