JNG-4872 Mapped transfer association relation test
BlackBeltTechnology/judo-runtime-core-jsl pull request #181
Opened 2023-05-25 16:03 UTC by gaborflorian

2023-05-26 14:47 UTC, robertcsakany approved these changes

2023-05-26 16:25 UTC, noherczeg approved these changes

2023-05-30 08:11 UTC, bencegelei requested changes

2023-05-30 08:11 UTC, bencegelei commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/transfer/MappedTransferAssociationTest.java
> +    public void testSingleRequeredRelationOnTransfer() {
Requered typo

2023-05-30 08:15 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/transfer/MappedTransferAssociationTest.java
> +    public void testSingleRequeredRelationOnTransfer() {
[c601c23](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/181/commits/c601c235549bc741ff4906bd4155e1bb98f81782)

2023-05-30 08:16 UTC, bencegelei approved these changes

2023-05-30 08:28 UTC, merged