JNG-4886 Validate for mapped entries
BlackBeltTechnology/judo-runtime-core-jsl pull request #192
Opened 2023-06-06 09:50 UTC by bencegelei

JNG-4886 Validate for mapped entries

2023-06-07 16:19 UTC, robertcsakany approved these changes

2023-06-08 07:43 UTC, Madmat8 approved these changes

2023-06-08 08:17 UTC, gaborflorian approved these changes

2023-06-08 16:27 UTC, noherczeg approved these changes

2023-06-08 17:31 UTC, robertcsakany requested changes

2023-06-08 17:31 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/resources/model/MappedTransferPrimitivesModel/MappedTransferPrimitives.jsl
> +////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Per-verse :) 👎

2023-06-08 21:10 UTC, bencegelei commented on judo-runtime-core-jsl-itest/src/test/resources/model/MappedTransferPrimitivesModel/MappedTransferPrimitives.jsl
> +////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[37741d7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/192/commits/37741d7efe0b69c3e537956cbb0d9eda47d8d36d)

2023-06-08 21:40 UTC, robertcsakany approved these changes

2023-06-09 07:02 UTC, gaborflorian approved these changes

2023-06-09 08:18 UTC, merged