JNG-4800 JSL model name with java keywords throw error on the psm-gen…
BlackBeltTechnology/judo-runtime-core-jsl pull request #197
Opened 2023-06-12 16:40 UTC by Madmat8

…erator

2023-06-12 18:43 UTC, robertcsakany approved these changes

2023-06-13 11:20 UTC, bencegelei requested changes

2023-06-13 11:20 UTC, bencegelei commented on pom.xml
> +        <judo-psm-generator-sdk-core-version>1.0.0.20230612_162055_53b22a7d_feature_JNG_4800_fix_jsl_model_name_with_java_keyword_throws_error</judo-psm-generator-sdk-core-version>
Version downgrading

2023-06-13 11:20 UTC, bencegelei commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/ModelNameWithJavaKeyword.java
> +    }
Please add least one assert to test

2023-06-13 12:26 UTC, Madmat8 commented on pom.xml
> +        <judo-psm-generator-sdk-core-version>1.0.0.20230612_162055_53b22a7d_feature_JNG_4800_fix_jsl_model_name_with_java_keyword_throws_error</judo-psm-generator-sdk-core-version>
[2cbc104](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/197/commits/2cbc1046eae050a4eae3c5fddb4d855da72067dc)

2023-06-13 12:26 UTC, Madmat8 commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/ModelNameWithJavaKeyword.java
> +    }
[e3c4d15](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/197/commits/e3c4d1573c75fd07f7f0e2835350da6ed81bea7f)

2023-06-13 12:38 UTC, gaborflorian approved these changes

2023-06-13 15:11 UTC, bencegelei approved these changes

2023-06-13 15:18 UTC, merged