JNG-4248 Add JSL SDK Tests for Filter / Page / Order
BlackBeltTechnology/judo-runtime-core-jsl pull request #215
Opened 2023-07-10 16:32 UTC by gaborflorian

2023-07-13 12:21 UTC, bencegelei approved these changes

2023-07-13 12:21 UTC, bencegelei commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +        // costume filter
costume 💃 or custom ?

2023-07-13 15:01 UTC, robertcsakany requested changes

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +        // filter for undefined
Add TODO and ticket number

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.stringAttr!ilike('TEST')")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedStringAttr!ilike('TEST')")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.dateAttr <= `2022-07-11`")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedStringAttr >= 'Another'")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.timestampAttr == `2022-07-11T19:09:33`")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.timestampAttr <= `2022-07-11T19:09:33`")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.timestampAttr > `1999-09-19T09:09:09`")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedTimestampAttr == `2022-07-11T19:09:33`")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedTimestampAttr <= `2022-07-11T19:09:33`")
The test intention is not clear

2023-07-13 15:01 UTC, robertcsakany commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedTimestampAttr > `1999-09-19T09:09:09`")
The test intention is not clear

2023-07-13 15:06 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.stringAttr!ilike('TEST')")
[84f9fe7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/215/commits/84f9fe72b4ee3131dbe69c0c6cdfa8153053415a)

2023-07-13 15:06 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedStringAttr!ilike('TEST')")
[84f9fe7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/215/commits/84f9fe72b4ee3131dbe69c0c6cdfa8153053415a)

2023-07-13 15:06 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.dateAttr <= `2022-07-11`")
[84f9fe7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/215/commits/84f9fe72b4ee3131dbe69c0c6cdfa8153053415a)

2023-07-13 15:07 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedStringAttr >= 'Another'")
[84f9fe7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/215/commits/84f9fe72b4ee3131dbe69c0c6cdfa8153053415a)

2023-07-13 15:07 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.derivedTimestampAttr > `1999-09-19T09:09:09`")
[84f9fe7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/215/commits/84f9fe72b4ee3131dbe69c0c6cdfa8153053415a)

2023-07-13 15:11 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +                .filterBy("this.timestampAttr <= `2022-07-11T19:09:33`")
[84f9fe7](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/215/commits/84f9fe72b4ee3131dbe69c0c6cdfa8153053415a)

2023-07-13 15:22 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/FiltersTest.java
> +        // filter for undefined
Added

2023-07-13 16:20 UTC, noherczeg approved these changes

2023-07-14 11:02 UTC, robertcsakany approved these changes

2023-07-14 11:23 UTC, merged