JNG-4221 When method use identifier have a method with identifiable
BlackBeltTechnology/judo-runtime-core-jsl pull request #257
Opened 2023-11-23 13:11 UTC by gaborflorian

2023-11-23 21:51 UTC, robertcsakany approved these changes

2023-11-24 09:10 UTC, Madmat8 approved these changes

2023-11-24 10:59 UTC, noherczeg approved these changes

2023-11-24 14:20 UTC, bencegelei requested changes

2023-11-24 14:20 UTC, bencegelei commented on judo-runtime-core-jsl-itest/models/SpecialCasesModel/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/SpecialCasesTest.java
> +    }
Function names are a bit confusing. Identifiable is the name of the interface that wraps UUID-s along with version and dto name. I recommend renaming these to `getUuidOf`.

However, instead of using this method, you could extract the UUID itself as a variable during testing since version and dto name is no longer "needed" while UUID will always be the same.

2023-11-24 17:17 UTC, gaborflorian commented on judo-runtime-core-jsl-itest/models/SpecialCasesModel/src/test/java/hu/blackbelt/judo/runtime/core/jsl/entity/SpecialCasesTest.java
> +    }
[f37926e](https://github.com/BlackBeltTechnology/judo-runtime-core-jsl/pull/257/commits/f37926eea2258f36b3ce91f13cf0c15cc24e709b)

2023-11-27 09:35 UTC, merged