JNG-4198 Remove ternary padding
BlackBeltTechnology/judo-runtime-core-jsl pull request #74
Opened 2022-10-28 15:47 UTC by bencegelei

JNG-4198 Remove ternary padding

2022-10-28 16:37 UTC, noherczeg requested changes

2022-10-28 16:37 UTC, noherczeg commented on judo-runtime-core-jsl-itest/src/test/resources/model/TernaryTest.jsl
> +    // derived BBB tb => TernaryTest::CCC!size() == 1 ? TernaryTest::CCC!any() : TernaryTest::DDD!any();
why keep comments?

2022-10-28 17:26 UTC, bencegelei commented on judo-runtime-core-jsl-itest/src/test/resources/model/TernaryTest.jsl
> +    // derived BBB tb => TernaryTest::CCC!size() == 1 ? TernaryTest::CCC!any() : TernaryTest::DDD!any();
Ticket numbers added

2022-10-28 17:28 UTC, noherczeg approved these changes

2022-10-29 16:14 UTC, robertcsakany approved these changes

2022-10-31 23:30 UTC, noherczeg approved these changes

2022-11-01 14:04 UTC, merged